version: '3.8'

services:
  api:
    build: .
    container_name: tqd-node
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - NODE_PORT=3000
      - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - .:/usr/src/app
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - esnet

  elasticsearch:
    container_name: tqd-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    restart: always

  kibana:
    container_name: tqd-kibana
    image: docker.elastic.co/kibana/kibana:8.7.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - esnet
    restart: always

volumes:
  esdata:

networks:
  esnet:
